site_name: Galaxy for Cedars-Sinai Medical Center
nav:
  - Home: index.md
  - Introduction: RNA-seq introduction.md
  - Primary analysis:
    - Introduction to primary analysis: Primary analysis introduction.md
    - Quality check: Quality check.md
    - Read processing: Trimming raw reads.md
  - Secondary analysis:
    - Alignment/Mapping: Alignment.md
    - Quantification of reads: Quantification.md
  - Tertiary analysis:
    - Introduction to tertiary analysis: Tertiary analysis introduction.md
    - Identification of differentially expressed features: Identification of DE features.md
    - DESeq2 output: DESeq2_output.md
    - Extraction and annotation of differentially expressed genes: Annotation of DE genes.md
    - Visualization of the differentially expressed genes: Visualization of DE genes.md
    - Analysis of functional enrichment among the differentially expressed genes:
      - Introduction to functional enrichment: Functional enrichment analysis of DE genes.md
      - GO pathway analysis: GO.md
      - KEGG pathway analysis: KEGG.md
site_url: https://artbio.github.io/springday/
repo_url: https://github.com/CedarsDSN/Galaxy_tutorial
theme: readthedocs
